.github/actions/setup-env/action.yml
.pre-commit-config.yaml
.prettierrc.yaml
README.md
docs/community/contribute.md
docs/get-started.md
docs/index.md
environment-dev.yml

If possible, I want to merge this before #100 to avoid too much noise afterwards. We can use the same hook to also format `.js` / `.css` / `.html` files that will be part of the repo after #61.

use prettier as markdown / yaml / toml formatter

---

ragna/_api/schemas.py

```python
from ragna.core import MessageRole
from ragna._api.schemas import Message
print(
Message(content="", role=MessageRole.SYSTEM).model_dump(mode="json")["timestamp"],
)
```
before
```
2023-10-23T19:46:11.258707Z
```
after
```
2023-10-23T19:46:37.082318
```

remove timezone offset from default timestamp of messages

---

ragna/_api/core.py
ragna/_api/schemas.py
ragna/core/_components.py
ragna/core/_rag.py
ragna/core/_utils.py
scripts/add_chats.py
tests/api/test_e2e.py
tests/utils.py

For the UI to know what parameters can be exposed to the user to tweak, we need to return this information from the API somehow. Fortunately, we are already using `pydantic` to validate the the `params` passed to each chat.
1. The `/components` endpoint now returns the JSON schema of each component. The name is behind the `"title"` key.
2. Following the same spirit, the `/components` endpoint now also returns a top level `"documents"` key that stores all supported suffixes.
Example:
```python
from pprint import pprint
import httpx
url = "http://127.0.0.1:31476"
token = (
httpx.post(f"{url}/token", data={"username": "foo", "password": "foo"})
.raise_for_status()
.json()
)
pprint(
httpx.get(f"{url}/components", headers={"Authorization": f"Bearer {token}"})
.raise_for_status()
.json(), …
```

return JSON schema of available components

---

tests/api/test_e2e.py
tests/utils.py

I'm seeing quite a few timeouts in #61. Using a too short timeout is recipe for flaky CI. Let's up it a little and hope that this is the end of it.

increase test timeout

---

ragna/_cli/core.py
tests/utils.py

Offline report from @dharhas. For simplicity when starting the UI, we also start the API as well as a worker if needed. However, we are not forwarding their log messages to the main thread. This makes it confusing for the user if an error happens, because there is trace of it in the console. This PR fixes that.

forward subprocess STDOUT / STDERR to main process

---

docs/install.md

@dharhas reported offline, that `pip install ragna[builtin]` doesn't work.
However, `pip install ragna[builtin]` works. In fact, this is what we use in CI to install our dependencies: https://github.com/Quansight/ragna/blob/a04efc2fbde3f44d541f6c49f84a92b4c91f2fc4/.github/actions/setup-env/action.yml#L61-L70
I don't have the actual error in front of me, but I'd wager a guess that something else than `bash` was used? 
In other shells, e.g. `zsh`, `[...]` has special meaning, There you would see
```
❯ pip install ragna[builtin]
zsh: no matches found: ragna[builtin]
```
Solution to this is simple: quote the offending part:
```
❯ pip install 'ragna[builtin]'
```
So this is a "user error". But I can see that this will be common enough. So let's just quote the installation instruction by …

quote the builtin install instructions

---

ragna/source_storages/_chroma.py

fix chroma only retrieving one source

---

pyproject.toml
ragna/core/_document.py
ragna/core/_rag.py
ragna/core/_utils.py
tests/core/test_rag.py

I've botched this in #104. Previously, we failed on unknown parameters as we should. But this option was removed from `merge_models`, but I failed to re-add it on the parameter unpacking. This PR reinstates it.

fix chat param unpacking

---

ragna/_cli/config.py
ragna/_cli/core.py
ragna/core/_config.py
ragna/core/_utils.py

This is my proposed solution for #124. It implements the following changes:
- Remove the `demo` and `builtin` special configuration options. Note that the previous `Config.demo()` is still available, since that just created a `Config()` with default values anyway:
https://github.com/Quansight/ragna/blob/a04efc2fbde3f44d541f6c49f84a92b4c91f2fc4/ragna/core/_config.py#L123-L125
- Remove the default value for `-c` / `--config`. `ragna worker`, `ragna api`, and `ragna ui` now require passing a configuration.
- Split `ragna config` and `ragna config --check` into `ragna init` and `ragna check`. `ragna init` is the configuration wizard and `ragna check` can be with configuration files to check availability of the requirements.
- Improve the wizard by printing a summary of the unmet requirements …

refactor config wizard

---

ragna/_api/core.py

This is a "better safe than sorry" PR that addresses #136. I still need to do a proper investigation if this is actually needed. However, the solution in this PR works flawlessly as reported by other users that faced the same issue. Thus, in interest of time, let's go with this for now, even it if its slightly less elegant.

dont create DB session as dependency

---

ragna/_api/core.py
ragna/core/_authentication.py
ragna/core/_config.py
ragna/core/_document.py

Without this, restarting the API will invalidate all active tokens up to this point, since they API has a new secret to verify them. The old default behavior is preserved. Meaning, if you don't set the `RAGNA_DEMO_AUTHENTICATION_SECRET` env var, we'll use a random on that changes with every start of the API.
This also removes the option to set the document upload secret for local documents through the configuration file. We shouldn't have done that in the first place. It can still be set through the same env var `RAGNA_API_DOCUMENT_UPLOAD_SECRET` as before.

allow API token secret to be set through env var

---

ragna/_ui/modal_configuration.py
ragna/_ui/styles.py

This PR is a quick fix to disable sliders in advanced config when the assistant or the source storage has "Ragna/Demo" in it.
Later we'll generate the advanced config dynamically based on the API result for the "components" endpoint (I actually have quite advanced work on that but I have a bug in Panel that prevents me from delivering a proper PR)

config quick fix : disable sliders if "Ragna/Demo"

---

ragna/source_storages/_chroma.py

Inline comment says it all. chroma-core/chroma#1205 for x-ref. Note that this doesn't affect the returned number of sources, since we limit them later based on the number of requested tokens.

Up the number of queried documents by Chroma

---

pyproject.toml
ragna/core/_document.py
tests/test_dependencies.py

The latest release removes the warning on import that we saw in #75.

pin pymupdf to latest release

---

ragna/assistants/_api.py

Relating to:
https://github.com/Quansight/ragna/issues/174
An improvement idea is that we can have streaming input check for those api that support this (e.g GPT). This way we know that it's still generating output rather than a network problem.

Update assistant timeout to accomodate longer response time.

---

ragna/core/_utils.py

Closes #181. `package_distributions` seems to involve heavy path operations that we only need to perform once. On my system, this nets us a 4x decrease in function calls and 2.5 seconds faster import. On slower file systems the latter number is probably even more pronounced. Benchmark in https://github.com/Quansight/ragna/issues/181#issuecomment-1802868433. 
Thanks @nenb for pointing this out!

cache importlib_metadata_package_distributions

---

ragna/source_storages/_lancedb.py

Fixes #193. 
`<rant>`
What a horrible UX that just let's the user pass nothing for the query in a vector search. I mean, what is the vector search supposed to do if it has nothing to compare against. :rage:
`</rant>`

fix LanceDB retrieval

---

ragna/assistants/_api.py
ragna/core/_components.py
ragna/source_storages/_chroma.py
ragna/source_storages/_demo.py
ragna/source_storages/_lancedb.py
ragna/source_storages/_vector_database.py

I feel it is kinda annoying to always pass a config when trying to instantiate a component, e.g. https://github.com/Quansight/ragna/issues/189#issuecomment-1804771900. There should be no harm to provide a default. When the components are instantiated for the queue we always pass a config
https://github.com/Quansight/ragna/blob/dc497ef4768b8f8bd4d5c3736eb1d67b27050387/ragna/core/_queue.py#L126-L130
Meaning, we can be sure that all components that are used "in process" receive the right config.

make config optional when creating a component

---

ragna/core/_document.py
ragna/core/_rag.py
tests/core/test_e2e.py
tests/core/test_rag.py
tests/source_storages/test_source_storages.py

The main change here is that users can no longer pass arbitrary objects to `rag.chat(documents=[...])`. This is now only allowed if `LocalDocument` is configured. So far I haven't found a use case to use this with anything else. If a use case arises later, we can always re-add it.

special case LocalDocument more

---

docs/how-tos/set-configuration.md

Small docs improvements to "Set Configuration" page
- add link to the referenced `Rag.chat()` function
- ~remove new line after `!!! note`~
- ~otherwise most markdown editors will recognize the block as a code block due to the 4 space indentation (same as #196)~
- **EDIT**: reverted due to `prettier` per review comments, c.f. https://github.com/Quansight/ragna/pull/197#pullrequestreview-1726123408
- fix typo: "instesd" -> "instead"

docs: small improvements to "Set Configuration" how-to

---

docs/tutorials/python-api.md

Several documentation improvements to the Python API tutorial
Originally started to fix the same note as #187, but noticed several other improvements that could be made
- additions:
- add link to the Python API reference
- add link to the FAQ for getting API keys
- stylistic improvements:
- simplifications:
- "databases are databases" is redundant
- "default configuration is applied by default" is redundant
- also remove redundant words like "that"; state directly instead
- see also [k8s style guide on direct language](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language) (which I use and reference often for docs -- it's a pretty great style guide!)
- remove duplications:
- remove duplicate "learn more" configuration link
- remove duplicate note on the …

docs: various improvements to Python API tutorial

---

ragna/deploy/_ui/central_view.py

Fixes #219. The issue here is that we are hardcoding some chat params, but we cannot guarantee that they are present. This should have been done together with #155.
In general, we don't want to hardcode anything in the UI in the near future, so this is a first step towards 3. of #217. The solution is not perfect as we are basically just displaying the name of the parameter variables rather than an adjusted human readable version, but it is good enough for now.

fix chat info

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Having these prefixes is redundant with our labels. We shouldn't have both.

remove [BUG] and [ENH] classifier from issue templates

---

ragna/deploy/_ui/central_view.py

Addressed #224. 20 visible documents is probably too high in most if not all cases, but at least it prevents the UI from becoming sluggish if one has 2k+ documents. Meaning, this does not prevent the "overflow" in most cases, but prevents a performance hit in the more extreme cases.

set hard limit of visible document pills

---

pyproject.toml
ragna/core/__init__.py
ragna/core/_document.py
ragna/deploy/_api/core.py
ragna/deploy/_api/schemas.py
ragna/deploy/_ui/resources/upload.js
scripts/add_chats.py
tests/deploy/api/test_e2e.py

Unfortunately, #186 was not enough. While we can use PUT to actually upload the document, other backends, e.g. AWS S3, need to use POST. To support both use cases, we extend the functionality of the document upload info to also return the method the end user needs to use. Basically, we are providing the full request parameters.

Make document upload method flexible

---

ragna/deploy/_ui/api_wrapper.py

1. `ApiWrapper.start_chat` is not called from anywhere but `ApiWrapper.start_and_prepare`. Since `.start_chat` is a single statement, I just inlined it.
2. Apart form the fact that one should not use mutable default values, `ApiWrapper.start_and_prepare` is only ever called with `params`. Thus, I removed the `params={}` default.
3. `emoji.emojize` handles multiple substitutions in a string just fine. There is no need for us to do it manually.

code quality improvements of the API wrapper

---

ragna/deploy/_ui/resources/upload.js

Fixes #176.
Batch concurrent file uploads from upload dialog to handle thousands of documents without browser lock ups.

fix large upload #176

---

ragna/deploy/_ui/central_view.py

Addresses #229. 
Currently a new chat info button is created whenever the UI is updated. This creates a problem as when the UI is re-rendered it is still referencing the original button (which has not actually been updated). To fix this issue a button should only be created once and then updated in place prior to each re-render.

Fix rendering of chat info button

---

ragna/deploy/_ui/central_view.py
ragna/deploy/_ui/styles.py

The more I look at our UI code, the more frustrated I grow about the way we define the `stylesheets` for the various panel components. Putting everything into one massive multiline string works, but has two downsides:
1. The formatting is all over the place, since the auto-formatters won't format it at all.
2. Inserting values is not easy, since in CSS braces, i.e. `{}`, are regular characters. Meaning, if we used f-strings, we would need to encode them all the time. We currently use `.format()` for this.
This PR adds a `stylesheets` function that takes two-tuples of CSS selectors and declarations. That way we can use regular Python syntax to define everything and fixing both issues above.
I've applied this to one instance of our code in this PR. If we move forward with this, I'll open an …

add functionality to format CSS stylesheets

---

ragna/deploy/_ui/central_view.py
ragna/deploy/_ui/styles.py
scripts/add_chats.py

While working on #215, I found it really difficult to add the change to the UI. For the most part I was confused how the chat interface was actually used. So I looked more into it with the goal of understanding how it works to be able to implement #215. And doing that lead to this PR, which majorly cleans up our code. 
There are still a few things I dislike, e.g. are calling private APIs of panel, but I think this is the best we can do for now. I've marked these places as `#TODO: @panel` to eventually discuss with them.

Cleanup UI code

---

environment-dev.yml
pyproject.toml
ragna/_compat.py
ragna/assistants/_anthropic.py
ragna/assistants/_api.py
ragna/assistants/_demo.py
ragna/assistants/_mosaicml.py
ragna/assistants/_openai.py
ragna/core/_components.py
ragna/core/_rag.py
ragna/deploy/_api/core.py
ragna/deploy/_ui/api_wrapper.py
ragna/deploy/_ui/central_view.py
tests/core/test_components.py
tests/deploy/api/test_e2e.py

Addresses the Python API part of #185.

implement streaming for assistants

---

ragna/deploy/_api/database.py
ragna/deploy/_api/orm.py
ragna/deploy/_api/schemas.py
ragna/deploy/_ui/app.py
ragna/deploy/_ui/central_view.py
ragna/deploy/_ui/right_sidebar.py
ragna/deploy/_ui/styles.py

Closes #248. Since we need to touch the database tables, this will not work with existing ones without handling. I'm going to open a separate issue for that. Edit: See #265.
I need help styling the accordion in the UI. By default it looks like
The color is off and the title doesn't seem to support Markdown. We don't actually need Markdown, but some way to make the part in `**...**` bold. When opening an item we also have another issue:
If long enough, the content of the first item happily expands behind the other items. We should probably make it scrollable.
@smeragoel is working on a design for this.

return source content from the REST API

---

environment-dev.yml

When I create the `mamba` environment via `mamba env create --file environment-dev.yml` and then install the project dependencies via `pyproject.toml`, `ipython` is broken for me.
Traceback:
```
Traceback (most recent call last):
File "/Users/nenb/miniforge3/envs/ragna-dev/bin/ipython", line 8, in <module>
sys.exit(start_ipython())
File "/Users/nenb/miniforge3/envs/ragna-dev/lib/python3.9/site-packages/IPython/__init__.py", line 129, in start_ipython
return launch_new_instance(argv=argv, **kwargs)
File "/Users/nenb/miniforge3/envs/ragna-dev/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance
app.start()
File "/Users/nenb/miniforge3/envs/ragna-dev/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 317, in start
self.shell.mainloop()
File …
```

Fix environment-dev.yml

---

ragna/_utils.py
ragna/deploy/_cli/core.py

Issue #277 asked for two small things:
1. Increase time to timeout from 30 seconds to 60 seconds
2. Add clarification to error message when timeout happens
This small pull request does those two things. 
Please let me know if I should add/change anything. All constructive feedback is welcome.

Increase API timeout and add custom message

---

docs/references/faq.md
ragna/assistants/__init__.py
ragna/assistants/_cohere.py

This addresses Issue #227 
As always, comments and change requests are welcome and encouraged

[ENH] - add support for Cohere assistants

---

ragna/deploy/_cli/config.py

When building the docs, we can see the following warning
```
INFO    -  DeprecationWarning: invalid escape sequence \[
File "/home/philip/git/ora/ragna/deploy/_cli/core.py", line 18, in <module>
from .config import ConfigOption, check_config, init_config
File "/home/philip/git/ora/ragna/deploy/_cli/config.py", line 216, in
f"$ pip install 'ragna\[all]'"
```
This comes from
https://github.com/Quansight/ragna/blob/8aa6bd09740be0bed6391fab00323caf4889f369/ragna/deploy/_cli/config.py#L211-L217
We need to escape the backslash there, since `rich` would otherwise interpret the `[all]` as [markup](https://rich.readthedocs.io/en/stable/markup.html#console-markup).
This PR uses the `rich` functionality to escape instead. This gives the same result for `rich`, but also resolves the warning.

fix invalid escape warning when building docs

---

ragna/deploy/_api/core.py

`await core_chat.answer(...)` is also called again inside the non-streaming block of code.

Remove duplicate call to answer method when not streaming

---

docs/index.md
environment-dev.yml
mkdocs.yml

Alternative to #323. We add a dev dependency, but I think that is worth it to avoid a lot of extra whitespace by increasing the tab width.

use truly-sane-lists plugin

---

.github/actions/setup-env/action.yml
.github/workflows/docker.yml
.github/workflows/lint.yml

Just caught this warning in CI: https://github.com/Quansight/ragna/actions/runs/7903868013?pr=320
This PR updates the outdated actions that we are using.

update outdated actions

---

pyproject.toml

Fixes #340. Thanks a ton @pavithraes for digging up the root cause.

ignore httpx deprecation warning

---

docs/references/config.md
docs/references/release-notes.md
ragna-docker.toml
ragna/deploy/_config.py

Supersedes #305. After an offline discussion with @aktech we agreed that it preferable to include the `config.api.root_path` in `config.api.url`. While this means we have this we have this information duplicated in the default configuration, this has two upsides:
1. We don't need to join the URL and the root path everywhere in our code base.
2. It opens up the possibility to route an app deployed with a root path to a top level domain without one.

use root_path in api.url

---

ragna/deploy/_ui/modal_configuration.py

This is a temporary fix for the Cohere assistants. Although in theory they support a 4k context window
https://github.com/Quansight/ragna/blob/8b0b0f3871b4f5929d1d02f9dd6aada06c4f3f67/ragna/assistants/_cohere.py#L12-L13
they seem to be using a very different tokenizer than what we use. When trying the assistant in the web UI with a document that actually supply 4k tokens, I get the following error message in the response
```
too many tokens: size limit exceeded by 1502 tokens. Try using shorter or fewer inputs, or setting prompt_truncation='AUTO'.
```
So the number of tokens actually differs by almost 40%.
In this PR I simply reduce the default number of tokens that we pull from the source storage to feed into the assistant. Setting this automatically depending on the assistant is a …

decrease default number of tokens in UI

---

environment-dev.yml
pyproject.toml
ragna/assistants/_ai21labs.py
ragna/assistants/_anthropic.py
ragna/assistants/_api.py
ragna/assistants/_cohere.py
ragna/assistants/_google.py
ragna/assistants/_mosaicml.py
ragna/assistants/_openai.py
tests/assistants/test_api.py
tests/conftest.py
tests/utils.py

I spend almost an hour today trying to find a bug that wasn't there, because we didn't raise a proper error when our API call failed.

improve error handling for builtin assistants

---

tests/deploy/api/test_e2e.py

Previously, we indeed tested `stream=True`, but we used the demo assistant to do it which does not support streaming. Meaning, we only ever got a single chunk from the API.
Test for this was proposed in https://github.com/Quansight/ragna/pull/317#pullrequestreview-1886007856.

add test for a streaming assistant

---

docs/examples/gallery_streaming.py
docs/references/release-notes.md
ragna/assistants/_ai21labs.py
ragna/assistants/_anthropic.py
ragna/assistants/_cohere.py
ragna/assistants/_demo.py
ragna/assistants/_google.py
ragna/assistants/_mosaicml.py
ragna/assistants/_openai.py
ragna/core/_components.py
tests/deploy/api/test_e2e.py

The abstract `Assistant.max_input_size` property was a left over from the prototype implementation we started from. The idea behind it was for to be able to automatically fill the context window, such that it is maxed out with the sources and the user prompt.
However, this makes quite a few assumptions, that held for our prototype, but are no longer true for Ragna:
- Our builtin `Chroma` and `LanceDB` have a parameter to pull a specific number of tokens
https://github.com/Quansight/ragna/blob/4a667f9aced1970f8eab8aa9e01aaf8c67b05db0/ragna/source_storages/_chroma.py#L80
https://github.com/Quansight/ragna/blob/4a667f9aced1970f8eab8aa9e01aaf8c67b05db0/ragna/source_storages/_lancedb.py#L94
but our demo source storage does not
https://github.com/Quansight/ragna/blob/4a667f9aced1970f8eab8aa9e01a …

remove max_input_size property from assistants

---

pyproject.toml

1. We renamed the file.
2. We should point at the release notes of the current stable release rather than the dev version.

fix release notes link in project metadata

---

docs/examples/gallery_streaming.py
pyproject.toml
ragna/assistants/_anthropic.py
ragna/assistants/_api.py
ragna/assistants/_google.py
ragna/assistants/_openai.py
ragna/deploy/_api/core.py
ragna/deploy/_ui/api_wrapper.py
requirements-docker.lock
tests/deploy/api/test_e2e.py

use JSONL streaming over SSE

---

README.md

Follow-up to #89 and #309. These links are broken as of now, since they point to the stable documentation, which will only include the resources after the 0.2.0 release.

fix doc links in README

---

docs/references/release-notes.md

Our current pipeline is not set up to push a `latest` tag
https://github.com/Quansight/ragna/blob/5a9bdf69de6b4234831532c0d13797a7015a61bf/.github/workflows/docker.yml#L67-L77
Will fix that after release given that latest is a meta tag anyway.

fix docker tag in release notes

---

ragna/deploy/_api/core.py
tests/deploy/api/test_components.py

updated get_component error message from 404 to 422

---

docs/examples/gallery_streaming.py
docs/tutorials/gallery_python_api.py
ragna/assistants/__init__.py
ragna/assistants/_anthropic.py

This PR addresses Issue #347 
Support (in Ragna) is changed from legacy ([Chat API](https://docs.anthropic.com/claude/reference/complete_post))or unsupported (by Anthropic) models to the [Anthropic Messages API](https://docs.anthropic.com/claude/reference/messages_post).
IMPORTANT: This PR should be merged before PR #381 and PR #376 are merged.

Update Anthropic assistants

---

ragna/deploy/_cli/config.py

After the pydantic 2.7 release (April 11 2024), which gets installed in CI since we only have a lower pin
https://github.com/Quansight/ragna/blob/f7de2e947c04cd3d4e8319cc117a8f9ecfa21239/pyproject.toml#L31-L33
a few typing errors popped up, e.g. https://github.com/Quansight/ragna/actions/runs/8676481873/job/23791035320?pr=389. It seems typing on these objects was made a little tighter and now we have to ignore more dynamic stuff. Fortunately, no functional changes.

fix mypy after pydantic 2.7

---

ragna/deploy/_ui/components/file_uploader.py
ragna/deploy/_ui/left_sidebar.py

Most of the links were already relative, but the two in this PR were not. `/imgs/...` and `imgs/...` are equivalent when Ragna is hosted at the root path, e.g. `127.0.0.1:31477`. If that is not the case, e.g. Ragna is hosted on `127.0.0.1:31477/behind/a/proxy`, `/imgs/` still points to `127.0.0.1:31477/imgs/`, whereas `imgs/` correctly points to `127.0.0.1:31477/behind/a/proxy/imgs`.

use relative links for all images in UI

---

README.md
docs/install.md

ragna has recently been brought to conda-forge; see [this feestock](https://github.com/conda-forge/ragna-feedstock) and the [package information](https://anaconda.org/conda-forge/ragna).
This PR
- addresses a TODO in the root's readme to add installation instructions via conda
- adds a button to access find the package on conda-forge, imitating the PyPI button

Add instructions to install from conda-forge.

---

ragna/deploy/_api/core.py
ragna/deploy/_api/database.py
ragna/deploy/_api/orm.py
ragna/deploy/_api/schemas.py
tests/deploy/api/test_e2e.py

This is an attempt at solving issue #399 
Using `lazy="joined"` on all the relationships was one way of doing it. I think we should use the alternative `joinedload` for more flexibility. It's kind of the same but we have the control over when we want to use it. 
I'd like your feedback on the performances in the various contexts you're using it. I've tested it locally, adding `echo=True` to `create_engine`. I could see that before this fix, there was a query to retrieve all chats, and then queries to get documents, messages and sources for each chat. After the fix, I see only one query to them all.
Unit tests are passing locally, except 2 but they seem related to my local setup

Fix #399 : eager loading of Chats docs, msgs, srcs

---

ragna/deploy/_api/core.py
ragna/deploy/_api/database.py
tests/deploy/api/test_batch_endpoints.py

Add multiple documents to the database in a single operation (`add_all`). This is important when there is non-negligible latency associated with each call to the database.

Add endpoint for batch uploading document metadata

---

pyproject.toml
ragna/deploy/_api/database.py
ragna/deploy/_api/orm.py

While looking into the lint issues of #401, I realized we never activated the SQLAlchemy mypy plugin. This PR makes up for that.
This surfaces some errors. When columns are defined without `nullable=False`, the value of the field is always `Optional[T]`. Since we don't have `None` values and won't have them for the currently available columns in the future, I've set `nullable=False` everywhere.

mypy for sqlalchemy

---

pyproject.toml

- Removes the ignore for a deprecation warning that came from `starlette`, but is fixed now.
- Adds a new ignore for deprecation warnings that were introduced by the latest release of `lancedb`. See lancedb/lancedb#1296

update ignored deprecation warnings

---

ragna/deploy/_api/core.py
ragna/deploy/_api/schemas.py

Basic prereq for passing chat history down the pipeline. History is already present in the `schema.Chat` object loaded from the database, so we just need to make sure it also gets loaded into the `ragna.core.Chat` object inside [schema_to_core_chat](https://github.com/Quansight/ragna/blob/647a61e3103cb2e54b7c5bc2da5df1e2906b059b/ragna/deploy/_api/core.py#L213).
https://github.com/Quansight/ragna/blob/647a61e3103cb2e54b7c5bc2da5df1e2906b059b/ragna/deploy/_api/core.py#L290-L297

Load message history to core chat from schema chat

---

ragna/core/_components.py
ragna/core/_rag.py
tests/core/test_rag.py

This PR changes two things:
1. The previous implementation for the extraction of the protocol models relied on the fact that the concrete subclasses use the exact same names for the protocol parameters, i.e. the parameters defined by the protocol base class. This is rather restricting, undocumented, and has bitten us before (https://github.com/Quansight/ragna/pull/369#issuecomment-2019756910). With this PR we identify the extra parameters by skipping the first `n` parameters in the concrete signature, where `n` is the number of protocol parameters.
2. Previously we just passed through the Pydantic validation error in case of a failure. While this contains all the information you need if you know the internals of Ragna, it is hard to parse for users. Especially, because they don't have any …

refactor protocol model extraction to only check extra parameters

---

docs/examples/gallery_streaming.py
docs/tutorials/gallery_custom_components.py
ragna/assistants/_ai21labs.py
ragna/assistants/_anthropic.py
ragna/assistants/_cohere.py
ragna/assistants/_demo.py
ragna/assistants/_google.py
ragna/assistants/_ollama.py
ragna/assistants/_openai.py
ragna/core/_components.py
ragna/core/_rag.py
ragna/deploy/_api/core.py
tests/assistants/test_api.py
tests/core/test_rag.py
tests/deploy/api/test_e2e.py
tests/deploy/utils.py

This is a very rough first pass at https://github.com/Quansight/ragna/issues/421. I decided to investigate the naive approach of replacing
```python
class Assistant
...
def answer(self, prompt: str, sources: list[Source]):
...
```
with
```python
class Assistant
...
def answer(self, messages: list[Message]):
...
```
for just the HTTP-like assistants as a POC. Since a `Message` instance can hold a list of `Source`s, the `_messages` list in `Rag.Chat` serves as a cache of raw messages that live in the database (and what the user sees), while each assistant is responsible for formatting the message list according to the needs of the individual LLM.

support chat history

---

ragna/deploy/_ui/left_sidebar.py

This PR modifies the `LeftSidebar` component to display chats in reverse order, showing the newest chats first instead of the oldest.
Should fix #391

#391 Chat Ordering based upon the order of interaction

---

environment-dev.yml
ragna/_utils.py
ragna/assistants/_ai21labs.py
ragna/assistants/_anthropic.py
ragna/assistants/_cohere.py
ragna/assistants/_google.py
ragna/assistants/_http_api.py
ragna/assistants/_ollama.py
ragna/assistants/_openai.py
tests/assistants/streaming_server.py
tests/assistants/test_api.py
tests/deploy/ui/test_ui.py
tests/utils.py

My patch in #425 is broken when using the Python API with `asyncio.run`, i.e. the regular use case. As implemented in #425, `break`ing out of the loop in `.answer()` means that the async iterator is not fully exhausted, i.e. `AsyncStopIteration` is never raised. This leads to the context manager that handles the HTTP request staying open longer than `Chat.answer`. When it is cleaned up eventually, internally it calls `await request.aclose()`. However, if at that point the async event loop is already killed, e.g. because the coroutine called by `asyncio.run` is finished, you'll get an error:
```
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<<async_generator_athrow without __name__>()> exception=RuntimeError('aclose(): asynchronous generator is already …
```

fix streaming handling for builtin assistants

---

.github/ISSUE_TEMPLATE/DOCKER_ISSUE_TEMPLATE.md
.github/workflows/update-docker-requirements.yml

Should Fix #458 
This PR updates the Docker requirements workflow to:
- Automatically create PRs to update requirements-docker.lock when changes are detected.
- Dynamically request reviews from the author and the person who merged the last PR into main.
I've also tested this updated workflow a number of times on my fork to- 
- Here's the [test workflow run](https://github.com/arjxn-py/ragna/actions/runs/10049115488/job/27774541367#step:6:1)
- Here's [the automatically created PR](https://github.com/arjxn-py/ragna/pull/6) when I bumped down `panel==1.4.2` on my fork for testing.

#458 Automate Docker Requirements Workflow for PR Creation and Review Requests

---

.github/ISSUE_TEMPLATE/DOCKER_ISSUE_TEMPLATE.md

Follow up on #459 
Related to #467 
cc: @pmeier 
Here's the issue surfaced upon failure on current changes: [https://github.com/arjxn-py/ragna/issues/12](https://github.com/arjxn-py/ragna/issues/12)

Fix docker requirement ci

---

ragna/core/_metadata_filter.py
tests/core/test_metadata_filter.py

The is a prerequisite for using `MetadataFilter` as part of FastAPI. I've scrapped the actual JSON serialization, because that would create JSON inside JSON with pydantic and pydantic knows how to serialize dicts anyway.

support pydantic (de)serialization on MetadataFilter

---

ragna/deploy/_api/database.py
ragna/source_storages/_chroma.py
ragna/source_storages/_demo.py
ragna/source_storages/_lancedb.py
tests/core/test_e2e.py
tests/deploy/api/test_e2e.py
tests/source_storages/test_source_storages.py

Developing with failing tests is a PITA. Instead of waiting for #461 to fix this, this PR does it upfront to help other work.

fix lint and test for corpus dev branch

---

ragna/core/_rag.py
tests/core/test_e2e.py

make Chat.prepare idempotent

---

ragna/deploy/_cli/core.py
tests/deploy/ui/test_ui.py

By default Python does not handle the SIGTERM signal. Thus, currently, when we send a SIGTERM to the process that was started by `ragna ui --start-api`, the `finally` branch that is supposed to stop the API is never run:
https://github.com/Quansight/ragna/blob/2066dcdeb949060873a8552449b848b245e0e985/ragna/deploy/_cli/core.py#L170-L173
Meaning, the Ragna API stays up:
```
❯ ragna ui --start-api &; sleep 10 && kill $! && sleep 10 && ps aux | grep ragna
[1] 22747
INFO:   RagnaDemoAuthentication: You can log in with any username and a matching password.
INFO:     Started server process [22773]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:31476 (Press CTRL+C to quit)
INFO:     127.0.0.1:54172 - "GET / …
```

gracefully stop API when started by ragna ui

---

docs/tutorials/gallery_custom_components.py
ragna/_docs.py

Follow-up to #496. If the documentation build errors and we never get to calling `RestApi.stop()`, we have a zombie RestAPI process. However, here it is even worse than for the tests in #496: since we are not randomizing the port number, the next time we build the docs, the old REST API is still available and will be picked up instead of starting a fresh one invalidating most of the assumptions that we make, e.g. no chats available after startup.

handle zombie processes in docs

---

ragna/core/_components.py
ragna/deploy/_api/core.py
ragna/source_storages/_chroma.py
ragna/source_storages/_demo.py
ragna/source_storages/_lancedb.py
tests/core/test_components.py
tests/deploy/api/test_e2e.py
tests/source_storages/test_source_storages.py

Addresses https://github.com/Quansight/ragna/issues/492

List corpuses

---

ragna/deploy/_cli/core.py
ragna/deploy/_cli/corpus.py

PoC that addresses #488.
Based on a [gist](https://gist.github.com/pmeier/cc1576839d3a25389080dc214640c397) produced by @pmeier, as well as comments from #488.
An example usage from the current branch is:
```
ragna corpus ingest $(find MY_DOCUMENT_DIRECTORY -type f) --metadata-fields metadata.json --corpus-name MY_CORPUS_NAME --user UNAME --report-failures 2>> failures.txt
cat metadata.json
```

488 corpus cli

---

ragna/deploy/_ui/central_view.py
ragna/deploy/_ui/css/chat_info/markdown.css

Fix #504 : honor the indentation in the MetadataFilter formatting

Fix #504 : honor the indentation in the MetadataFilter formatting 

---

ragna/deploy/_core.py

1. If there is no browser available, we can't open one.
2. Since the health check is coming from the same machine and thus doesn't see any proxy, we cannot use `config._url` since that includes the `root_path`.

fix open browser functionality

---

docs/tutorials/gallery_python_api.py
pyproject.toml
ragna-docker.toml
ragna/source_storages/__init__.py
ragna/source_storages/_qdrant.py
tests/source_storages/test_source_storages.py

This PR adds support for Qdrant - https://qdrant.tech/ to be used as RAG storage.

feat: Qdrant RAG Storage

---

pyproject.toml
ragna/source_storages/_chroma.py
ragna/source_storages/_lancedb.py
ragna/source_storages/_vector_database.py
tests/source_storages/test_source_storages.py

This partially addresses #523 by updating the ChromaDB version to the latest 0.6.1 and patching particular test cases where ChromaDB's behavior differs from other databases.

Upgrade ChromaDB to >=0.6.0 and fix broken tests

---

SECURITY.md
docs/index.md

There was a [`TODO`](https://github.com/Quansight/ragna/blob/91124ad81b3c25715e5229787bedea55d959a95e/docs/index.md?plain=1#L23-L24) that said that we want to change the sections on the front page under Key Features to [cards](https://squidfunk.github.io/mkdocs-material/reference/grids/#list-syntax). This PR accomplishes that
This PR also fixes links (fix #508) that were broken

Use cards instead sections for Key Features portion of front page

---

.readthedocs.yml
docs/tutorials/gallery_python_api.py
ragna/source_storages/__init__.py

Partially addresses #529
This PR solves build failures on Read The Docs by telling git to ignore files that mkdocs/read the docs changes.
This PR __does not__ solve the underlying issue with non-editable installs.
[Preview the successfully built docs here](https://ragna--539.org.readthedocs.build/en/539/)

Fix MkDocs build

---

pyproject.toml

This fixes #529 by changing the naming scheme for wheels created for non-editable installation

Fix non-editable install

---

.github/actions/setup-env/action.yml

This resolves #543 by explicitly removing the implicitly used `defaults` Conda channel.
See [the documentation for the GitHub action](https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-14-remove-defaults-channel) for reference.

[FIX] Remove `defaults` channel from Conda environments in CI

---

tests/assistants/test_api.py

The changes included in this PR make the tests more resilient against misconfigured local DNS by using `127.0.0.1` instead of `localhost`.

Protect against local DNS misconfiguration

---

ragna/core/_document.py
ragna/deploy/_api.py
ragna/deploy/_database.py
ragna/deploy/_engine.py
ragna/deploy/_orm.py
ragna/deploy/_schemas.py
tests/deploy/api/test_components.py
tests/deploy/api/test_endpoints.py
tests/deploy/api/utils.py

This PR partially addresses #466 and supersedes certain respective parts of #486.
The new endpoints, all using the `GET` method, in this PR are as follow:
- `/documents`
- `/documents/{id}`
- `/documents/{id}/content`
Additionally, we now include MIME types in `ragna.core.Document`s.
A test utility `upload_documents` is also introduced for convenience when writing tests for endpoints.
Much of the code in this PR is copied from or inspired by @blakerosenthal's #486

[ENH] Add `GET` endpoints for documents

---

.gitattributes
.gitignore

Add a few lines to `.gitignore` and `.gitattributes` for a better experience for developers of Ragna who are using [Pixi](https://pixi.sh/).

Add lines to git-related files for Pixi

---

ragna/source_storages/_qdrant.py
tests/source_storages/test_source_storages.py

This PR parallelizes fetching metadata for Qdrant for performance purposes. It parallelizes both across corpuses, as well as across pages of metadata for a given corpus.
Tests are also modified so that test corpuses are large enough to necessarily require pagination.
#557 is addressed in the process of implementing the fetching of metadata for a given corpus.

Parallelize fetching metadata for Qdrant

---

pyproject.toml

Temporarily change `panel[fastapi]` dependency to `panel` together with `bokeh-fastapi`
Temporarily fixes #565

Temporary fix for docker requirements

---

.github/workflows/update-docker-requirements.yml

Gives the developer feedback when making changes to dependencies so as not to break the generation of [`requirements-docker.lock`](https://github.com/Quansight/ragna/blob/main/requirements-docker.lock)

Run `update-docker-requirements.yml` on pull request for feedback

---

.github/actions/setup-env/action.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.readthedocs.yml
Dockerfile
docs/community/contribute.md
pixi.lock
pyproject.toml
ragna-docker.toml

This PR migrates Ragna to use Pixi instead of Conda/Mamba.
Changes include using Pixi configuration and all package dependencies in `pyproject.toml`. 
CI workflows are also migrated. 
Remaining tasks:
I can also [automatically update lockfiles](https://pixi.sh/dev/integration/ci/updates_github_actions/) if @pmeier thinks it would be useful.

Migrate to Pixi

---

.github/workflows/test.yml
Dockerfile
pixi.lock
pyproject.toml

Adds support for Python 3.13 after fixing PyMuPDF segfaults in #586.
Also adds `"ignore::SyntaxWarning"` to Pytest filterwarnings. See https://github.com/qdrant/qdrant-client/issues/983

Add support for Python 3.13
