Quansight/ragna

.readthedocs.yml

Also, verify that build preview is triggered

Fix .readthedocs.yml to use conda

---

.pre-commit-config.yaml
examples/local_llm/local_llm.ipynb
examples/python_api/python_api.ipynb
examples/s3_documents/s3_documents.ipynb
pyproject.toml
ragna/_api/core.py
ragna/_api/database.py
ragna/_cli/config.py
ragna/_cli/core.py
ragna/assistants/__init__.py
ragna/assistants/_api.py
ragna/assistants/_openai.py
ragna/core/__init__.py
ragna/core/_authentication.py
ragna/core/_components.py
ragna/core/_config.py
ragna/core/_document.py
ragna/core/_queue.py
ragna/core/_rag.py
ragna/core/_utils.py
ragna/source_storages/__init__.py
ragna/source_storages/_chroma.py
ragna/utils/__init__.py
ragna/utils/_chunk.py
ragna/utils/_misc.py
scripts/add_chats.py
scripts/update_optional_dependencies.py
tests/api/test_e2e.py
tests/core/test_e2e.py
tests/test_utils.py

With the release of `ruff format`, we don't need anything else anymore :tada:

ruff everywhere

---

pyproject.toml
ragna/source_storages/_chroma.py
ragna/source_storages/_lancedb.py
ragna/source_storages/_vector_database.py

Closes #71. This moves the tokenizer as well as the embedding function to a common base class.

add common vector DB base class

---

.github/actions/setup-env/action.yml
docs/community/contribute.md
docs/install.md
pyproject.toml
ragna/_cli/config.py
scripts/update_optional_dependencies.py

Recommend [builtin] for installation

---

ragna/_api/database.py

make DB connect_args type specific

---

environment-dev.yml
mkdocs.yml

@pavithraes I'm merging this on my own to have the analytics now. Let's revert if you disagree.

add plausible analytics

---

ragna/assistants/_demo.py

clarify demo assistant message

---

docs/tutorials/python-api.md

fix Ragna 101

---

ragna/_api/core.py
ragna/_cli/config.py
ragna/_ui/app.py
ragna/_utils.py
ragna/core/_config.py

Make API / UI origins configurable

---

ragna/core/_authentication.py

It might still be non-obvious how to login, but this is a start.

add print for demo auth

---

docs/assets/stylesheet.css
docs/overrides/main.html
docs/references/changelog.md
mkdocs.yml

Ref:
It will be hidden on scroll, and can be dismissed

Add announcement banner with link to blog

---

docs/tutorials/python-api.md

before:
after:
Thanks @jaimergp for the report!

fix note in Ragna 101

---

pyproject.toml

- `main`: `0.1.2.dev15+g4dfef38ls_scm`
- PR: `0.2.0.dev16+gf9e687a`

change version scheme to increase the minor instead of patch version

---

ragna/deploy/_api/core.py
ragna/deploy/_api/schemas.py
ragna/deploy/_ui/api_wrapper.py
ragna/deploy/_ui/central_view.py
tests/deploy/api/test_e2e.py

don't return full chat as part of message output

---

pyproject.toml

Bump panel minimum version

---

ragna/core/__init__.py
ragna/core/_document.py

Added support for the markdown extension as per [issue #210](https://github.com/Quansight/ragna/issues/210)
Please let me know if any other changes are needed!

Add support for markdown files (#210)

---

ragna/deploy/_ui/app.py

Potential fix for #275. Let's see. Even if its not, this change is still viable.

add forward slashes to the auth and logout endpoints

---

.github/workflows/update-docker-requirements.yml

Follow-up to #283 to automatically update the requirements. Basically, we only need to dispatch the workflow and a bot will open a PR for us.

add workflow to update the docker requirements

---

.github/workflows/update-docker-requirements.yml

Same reasoning as https://github.com/Quansight/ragna/pull/288#issuecomment-1904075821.

add workflow actor as reviewer rather than assignee

---

.readthedocs.yml
scripts/docs/rtd.py

While I did this mostly for pypa/setuptools_scm#962, I think it is a good idea in general to monitor what RTD is injecting during its build.

RTD git debug

---

docs/references/python-api.md
ragna/deploy/__init__.py

re-add Authentication documentation

---

docs/references/faq.md

I was doing some research for a grant proposal and I thought the results would look good in our FAQ as well.

add 'why should I use Ragna?' to FAQ

---

Dockerfile

set LanceDB config dir in Dockerfile

---

Dockerfile
ragna/deploy/_cli/core.py
ragna/deploy/_ui/app.py

@aktech With this you can pass `--no-open-browser`.

add option to not open the browser when starting the web UI

---

README.md
docs/index.md

Closes #243 
Note: Add @Tengal-Teemo, the video creator, as a co-author when merging. :)

Add overview video to docs & README

---

docs/references/faq.md

fix typo in FAQ

---

ragna/deploy/_ui/central_view.py

break recursion cycle for chat message repr

---

docs/references/release-notes.md

Cc @pavithraes. Will merge on my own.

add more release notes for 0.2.0

---

scripts/add_chats.py

Before #215, we needed to send the prompt as parameter. Now it needs to be send as JSON.

fix add_chats.py script

---

environment-dev.yml
ragna/assistants/_api.py

Smooth upgrade with just a few ignores removed. cc @smokestacklightnin

bump mypy to 1.10

---

ragna/deploy/_ui/central_view.py

Fix CopyToCliboard functionality in UI

---

ragna/deploy/_ui/css/left_sidebar/button.css

adding back the chat bubble that disappeared when I refactored the CSS

Fix #415 : chat bubble

---

ragna/core/__init__.py
ragna/core/_metadata_filter.py
tests/core/test_metadata_filter.py

add metadata filter

---

ragna/_cli/core.py
ragna/deploy/_core.py
tests/deploy/api/utils.py

re-enable browser opening functionality 

---

docs/references/release-notes.md

I'd like to include #436 into this release as well. Unless merging it is blocked for some reason, I'll update this PR afterwards.

add release notes for v0.2.1

---

.github/workflows/update-docker-requirements.yml
pyproject.toml

cc @arjxn-py Just a test for your patch in #459. If all goes well, we should see a PR being opened against `main` and I should be pinged on it.

try docker requirements update

---

pyproject.toml

trigger docker reqs workflow

---

.github/ISSUE_TEMPLATE/DOCKER_ISSUE_TEMPLATE.md
.github/workflows/update-docker-requirements.yml
pyproject.toml

Follow-up to https://github.com/Quansight/ragna/pull/467#issuecomment-2267662822.
cc @arjxn-py

fix docker requirements update workflow

---

ragna/source_storages/_chroma.py
tests/source_storages/test_source_storages.py

Chroma does not allow to use the `$and` or `$or` operator on single element filters.

don't use reduction on single element in Chroma

---

ragna/deploy/_api/core.py
ragna/deploy/_api/database.py

Per title for #484. This just extracts this patch out that are independent of the metadata filter UI.

minor API fixes in preparation of the metadata filter UI

---

ragna/core/_components.py
ragna/deploy/_api/core.py
ragna/source_storages/_chroma.py
ragna/source_storages/_demo.py
ragna/source_storages/_lancedb.py
tests/deploy/api/test_e2e.py
tests/source_storages/test_source_storages.py

Addresses the API part of https://github.com/Quansight/ragna/issues/493.

add list_metadata functionality to web API

---

.github/actions/setup-env/action.yml

try fix Windows CI

---

tests/source_storages/test_source_storages.py

I forgot to re-enable this when debugging in #519. This is needed to trigger the error reported in #523 cc @smokestacklightnin

reenable source storage tests

---

pyproject.toml
ragna/source_storages/_qdrant.py

@Anush008 I messed up and forgot to approve running CI in #524. As a result, some failures went undetected:
1. When calling `list_metadata()` with a corpus, there was no check whether the former actually exist. Thus, I've added a call to `_ensure_table`.
2. There were plenty of `mypy` errors that I addressed.

Fix Qdrant source storage

---

docs/references/faq.md

This mini PR addresses #549 by changing the heading containing an `X` to an ellipsis `...`.

[FIX] Change `X` to ellipsis `...`

---

ragna/deploy/_database.py

Filter out null bytes from source content

---

pyproject.toml
ragna/source_storages/_chroma.py
ragna/source_storages/_vector_database.py

Sister PR to #563. Both together should fix all CI issues seen for example in #562.

update chroma to 1.*

---

pixi.lock
pyproject.toml

Resolves #579 by putting the [correct config](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license) in the pyproject.toml file.

Fix project license config to use SPDX epxression
